export const TEST_ACTION = 'TEST_ACTION';
export const REQUEST_TEST_ACTION = 'REQUEST_TEST_ACTION';
export const SUCCESS_TEST_ACTION = 'SUCCESS_TEST_ACTION';
export const FAILED_TEST_ACTION = 'FAILED_TEST_ACTION';